export {};
// This file is automatically generated.
// Please do not edit this file directly.

// This file is part of the Express framework.
// It is subject to the terms and conditions defined in

declare global {
  /**
   * The base URL of the application.
   */
  var BASE_URL: string;

  /**
   * The URL of the application. Without its base URL and the query string.
   */
  var PATH_URL: string;

  /**
   * The query string of the application.
   */
  var QUERY_URL: string;
}
